import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import LinkNav from "_consts/link_nav";

const Home: NextPage = () => {
    const [navLinks, setNavLinks] = useState<JSX.Element[]>([]);

    useEffect(() => {
        const navLinks = Object.entries(LinkNav).map((item, k) => {
            return (
                <Link href={item[1].link} key={k}>
                    <a>{item[1].title}</a>
                </Link>
            );
        });
        setNavLinks(navLinks);
    }, []);

    return (
        <>
            <Head>
                <title>Solana Program Library</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Solana Program Library</h1>
                <nav>{navLinks}</nav>
            </main>
        </>
    );
};

export default Home;
