import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import LinkNav from "_consts/link_nav";
import LinkNavCookBook from "_consts/link_nav_cook_book";
import { T_NAV } from "_consts";

const funcNavSet = (ListLinks: T_NAV): JSX.Element[] => {
    const res = Object.entries(ListLinks).map((i, k) => {
        return (
            <Link key={k} href={i[1].link}>
                <a>{i[1].title}</a>
            </Link>
        );
    });
    return res;
};

const Home: NextPage = () => {
    const [navLinks, setNavLinks] = useState<JSX.Element[]>([]);
    const [navLinksCookBook, setNavLinksCookBook] = useState<JSX.Element[]>([]);

    useEffect(() => {
        setNavLinks(funcNavSet(LinkNav));
        setNavLinksCookBook(funcNavSet(LinkNavCookBook));
    }, []);

    return (
        <>
            <Head>
                <title>Solana Program Library</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Solana Program Library</h1>
                <nav>{navLinks}</nav>

                <h1>Cook book</h1>
                <nav>{navLinksCookBook}</nav>
            </main>
        </>
    );
};

export default Home;
